/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MultiplayerImport } from './routes/multiplayer'
import { Route as CatchImport } from './routes/catch'
import { Route as IndexImport } from './routes/index'
import { Route as BattleBattleIdImport } from './routes/battle.$battleId'

// Create/Update Routes

const MultiplayerRoute = MultiplayerImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRoute,
} as any)

const CatchRoute = CatchImport.update({
  id: '/catch',
  path: '/catch',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BattleBattleIdRoute = BattleBattleIdImport.update({
  id: '/battle/$battleId',
  path: '/battle/$battleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/catch': {
      id: '/catch'
      path: '/catch'
      fullPath: '/catch'
      preLoaderRoute: typeof CatchImport
      parentRoute: typeof rootRoute
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerImport
      parentRoute: typeof rootRoute
    }
    '/battle/$battleId': {
      id: '/battle/$battleId'
      path: '/battle/$battleId'
      fullPath: '/battle/$battleId'
      preLoaderRoute: typeof BattleBattleIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catch': typeof CatchRoute
  '/multiplayer': typeof MultiplayerRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catch': typeof CatchRoute
  '/multiplayer': typeof MultiplayerRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/catch': typeof CatchRoute
  '/multiplayer': typeof MultiplayerRoute
  '/battle/$battleId': typeof BattleBattleIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catch' | '/multiplayer' | '/battle/$battleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catch' | '/multiplayer' | '/battle/$battleId'
  id: '__root__' | '/' | '/catch' | '/multiplayer' | '/battle/$battleId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatchRoute: typeof CatchRoute
  MultiplayerRoute: typeof MultiplayerRoute
  BattleBattleIdRoute: typeof BattleBattleIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchRoute: CatchRoute,
  MultiplayerRoute: MultiplayerRoute,
  BattleBattleIdRoute: BattleBattleIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/catch",
        "/multiplayer",
        "/battle/$battleId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/catch": {
      "filePath": "catch.tsx"
    },
    "/multiplayer": {
      "filePath": "multiplayer.tsx"
    },
    "/battle/$battleId": {
      "filePath": "battle.$battleId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
